# This file is a template, and might need editing before it works on your project.
image: golang:latest

variables:
  # Please edit to your GitLab project
  REPO_NAME: gitlab.aws.dev/devops-aws/tecli

# The problem is that to be able to use go get, one needs to put
# the repository in the $GOPATH. So for example if your gitlab domain
# is gitlab.com, and that your repository is namespace/project, and
# the default GOPATH being /go, then you'd need to have your
# repository in /go/src/gitlab.com/namespace/project
# Thus, making a symbolic link corrects this.
before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
  - info
  - build
  - release

info:
  stage: info
  script:
    - make go/version go/env

build:
  stage: build
  script:
    - make gitlab/build
  artifacts:
    paths:
      - build/tecli

release_darwin_amd64:
  only:
    refs:
      - master
      - tags
  stage: release
  script:
    - make gitlab/release/darwin/amd64
  artifacts:
    paths:
      - dist/tecli-darwin-amd64

release_solaris_amd64:
  only:
    refs:
      - master
      - tags
  stage: release
  script:
    - make gitlab/release/solaris/amd64
  artifacts:
    paths:
      - dist/tecli-solaris-amd64

release_freebsd_386:
  only:
    refs:
      - master
      - tags
  stage: release
  script:
    - make gitlab/release/freebsd/386
  artifacts:
    paths:
      - dist/tecli-freebsd-386

release_freebsd_amd64:
  only:
    refs:
      - master
      - tags
  stage: release
  script:
    - make gitlab/release/freebsd/amd64
  artifacts:
    paths:
      - dist/tecli-freebsd-amd64

release_freebsd_arm:
  only:
    refs:
      - master
      - tags
  stage: release
  script:
    - make gitlab/release/freebsd/arm
  artifacts:
    paths:
      - dist/tecli-freebsd-arm

release_openbsd_386:
  only:
    refs:
      - master
      - tags
  stage: release
  script:
    - make gitlab/release/openbsd/386
  artifacts:
    paths:
      - dist/tecli-openbsd-386

release_openbsd_amd64:
  only:
    refs:
      - master
      - tags
  stage: release
  script:
    - make gitlab/release/openbsd/amd64
  artifacts:
    paths:
      - dist/tecli-openbsd-amd64

release_openbsd_arm:
  only:
    refs:
      - master
      - tags
  stage: release
  script:
    - make gitlab/release/openbsd/arm
  artifacts:
    paths:
      - dist/tecli-openbsd-arm

release_linux_386:
  only:
    refs:
      - master
      - tags
  stage: release
  script:
    - make gitlab/release/linux/386
  artifacts:
    paths:
      - dist/tecli-linux-386

release_linux_amd64:
  only:
    refs:
      - master
      - tags
  stage: release
  script:
    - make gitlab/release/linux/amd64
  artifacts:
    paths:
      - dist/tecli-linux-amd64

release_linux_arm:
  only:
    refs:
      - master
      - tags
  stage: release
  script:
    - make gitlab/release/linux/arm
  artifacts:
    paths:
      - dist/tecli-linux-arm

release_windows_386:
  only:
    refs:
      - master
      - tags
  stage: release
  script:
    - make gitlab/release/windows/386
  artifacts:
    paths:
      - dist/tecli-windows-386

release_windows_amd64:
  only:
    refs:
      - master
      - tags
  stage: release
  script:
    - make gitlab/release/windows/amd64
  artifacts:
    paths:
      - dist/tecli-windows-amd64
