use: configure [delete]
example: >
  If you want to create a new named profile:
    tecli configure --profile work
    
  If you want to delete a named profile:
    tecli configure delete --profile work
short: Configures tecli global settings
long: Configures tecli global credentials and configurations used by commands